-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.achievements
(
    achievement_id uuid NOT NULL DEFAULT gen_random_uuid(),
    student_id text COLLATE pg_catalog."default",
    title character varying(300) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    achievement_date date NOT NULL,
    category character varying(100) COLLATE pg_catalog."default",
    is_verified boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT achievements_pkey PRIMARY KEY (achievement_id)
);

CREATE TABLE IF NOT EXISTS public.certifications
(
    certification_id uuid NOT NULL DEFAULT gen_random_uuid(),
    student_id text COLLATE pg_catalog."default",
    name character varying(300) COLLATE pg_catalog."default" NOT NULL,
    issuing_organization character varying(200) COLLATE pg_catalog."default" NOT NULL,
    issue_date date NOT NULL,
    expiry_date date,
    credential_id character varying(200) COLLATE pg_catalog."default",
    credential_url character varying(500) COLLATE pg_catalog."default",
    is_verified boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT certifications_pkey PRIMARY KEY (certification_id)
);

CREATE TABLE IF NOT EXISTS public.club_invitations
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    club_id uuid NOT NULL,
    student_id text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    responded_at timestamp with time zone,
    responded_by uuid,
    role text COLLATE pg_catalog."default",
    CONSTRAINT club_invitations_pkey PRIMARY KEY (id),
    CONSTRAINT uq_club_student UNIQUE (club_id, student_id)
);

CREATE TABLE IF NOT EXISTS public.club_memberships
(
    club_id uuid NOT NULL,
    student_id text COLLATE pg_catalog."default" NOT NULL,
    role character varying(100) COLLATE pg_catalog."default",
    start_date date NOT NULL,
    end_date date,
    is_active boolean DEFAULT true,
    CONSTRAINT club_memberships_pkey PRIMARY KEY (club_id, student_id, start_date)
);

CREATE TABLE IF NOT EXISTS public.clubs
(
    club_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    category character varying(100) COLLATE pg_catalog."default",
    established_date date,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT clubs_pkey PRIMARY KEY (club_id),
    CONSTRAINT clubs_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.companies
(
    company_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    website character varying(255) COLLATE pg_catalog."default",
    industry character varying(100) COLLATE pg_catalog."default",
    size character varying(50) COLLATE pg_catalog."default",
    location character varying(200) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT companies_pkey PRIMARY KEY (company_id),
    CONSTRAINT companies_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.company_job_roles
(
    job_role_id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    requirements text COLLATE pg_catalog."default",
    salary_range character varying(100) COLLATE pg_catalog."default",
    location character varying(200) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    role_type offer_type,
    CONSTRAINT company_job_roles_pkey PRIMARY KEY (job_role_id)
);

CREATE TABLE IF NOT EXISTS public.departments
(
    department_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT departments_pkey PRIMARY KEY (department_id),
    CONSTRAINT departments_code_key UNIQUE (code),
    CONSTRAINT departments_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.etl_runs
(
    run_id uuid NOT NULL DEFAULT gen_random_uuid(),
    operation_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp with time zone,
    records_processed integer DEFAULT 0,
    error_message text COLLATE pg_catalog."default",
    metadata jsonb,
    CONSTRAINT etl_runs_pkey PRIMARY KEY (run_id)
);

CREATE TABLE IF NOT EXISTS public.faculty
(
    faculty_id uuid NOT NULL DEFAULT gen_random_uuid(),
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    department_id uuid,
    designation character varying(100) COLLATE pg_catalog."default",
    specialization text COLLATE pg_catalog."default",
    avatar_path character varying(500) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT faculty_pkey PRIMARY KEY (faculty_id),
    CONSTRAINT faculty_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.interests
(
    interest_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category character varying(50) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT interests_pkey PRIMARY KEY (interest_id),
    CONSTRAINT interests_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.internships
(
    internship_id uuid NOT NULL DEFAULT gen_random_uuid(),
    student_id text COLLATE pg_catalog."default",
    company_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date,
    description text COLLATE pg_catalog."default",
    is_verified boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT internships_pkey PRIMARY KEY (internship_id)
);

CREATE TABLE IF NOT EXISTS public.match_settings
(
    setting_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    skill_weight numeric(3, 2) DEFAULT 0.30,
    cgpa_weight numeric(3, 2) DEFAULT 0.25,
    attendance_weight numeric(3, 2) DEFAULT 0.20,
    interest_weight numeric(3, 2) DEFAULT 0.25,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT match_settings_pkey PRIMARY KEY (setting_id),
    CONSTRAINT match_settings_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.migration_logs
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    migration_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    executed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    error_message text COLLATE pg_catalog."default",
    execution_time_ms integer,
    CONSTRAINT migration_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.placement_invitations
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL,
    job_role_id uuid,
    student_id text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    responded_at timestamp with time zone,
    responded_by uuid,
    CONSTRAINT placement_invitations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.placements
(
    placement_id uuid NOT NULL DEFAULT gen_random_uuid(),
    student_id text COLLATE pg_catalog."default",
    company_id uuid,
    job_role_id uuid,
    status placement_status NOT NULL,
    applied_date date NOT NULL,
    shortlisted_date date,
    offered_date date,
    accepted_date date,
    rejected_date date,
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    offer_type offer_type,
    CONSTRAINT placements_pkey PRIMARY KEY (placement_id)
);

CREATE TABLE IF NOT EXISTS public.publications
(
    publication_id uuid NOT NULL DEFAULT gen_random_uuid(),
    student_id text COLLATE pg_catalog."default",
    title character varying(500) COLLATE pg_catalog."default" NOT NULL,
    authors text COLLATE pg_catalog."default",
    journal_conference character varying(300) COLLATE pg_catalog."default",
    publication_date date,
    doi character varying(200) COLLATE pg_catalog."default",
    url character varying(500) COLLATE pg_catalog."default",
    is_verified boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT publications_pkey PRIMARY KEY (publication_id)
);

CREATE TABLE IF NOT EXISTS public.research_project_participants
(
    project_id uuid NOT NULL,
    student_id text COLLATE pg_catalog."default" NOT NULL,
    role character varying(100) COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    CONSTRAINT research_project_participants_pkey PRIMARY KEY (project_id, student_id)
);

CREATE TABLE IF NOT EXISTS public.research_project_required_skills
(
    project_id uuid NOT NULL,
    skill_id uuid NOT NULL,
    CONSTRAINT research_project_required_skills_pkey PRIMARY KEY (project_id, skill_id)
);

CREATE TABLE IF NOT EXISTS public.research_projects
(
    project_id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(300) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    faculty_id uuid,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'ACTIVE'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT research_projects_pkey PRIMARY KEY (project_id)
);

CREATE TABLE IF NOT EXISTS public.skills
(
    skill_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category character varying(50) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT skills_pkey PRIMARY KEY (skill_id),
    CONSTRAINT skills_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.student_interests
(
    student_id text COLLATE pg_catalog."default" NOT NULL,
    interest_id uuid NOT NULL,
    student_description text COLLATE pg_catalog."default",
    CONSTRAINT student_interests_pkey PRIMARY KEY (student_id, interest_id)
);

CREATE TABLE IF NOT EXISTS public.student_skills
(
    student_id text COLLATE pg_catalog."default" NOT NULL,
    skill_id uuid NOT NULL,
    proficiency_level character varying(20) COLLATE pg_catalog."default" DEFAULT 'INTERMEDIATE'::character varying,
    acquired_date date DEFAULT CURRENT_DATE,
    student_description text COLLATE pg_catalog."default",
    CONSTRAINT student_skills_pkey PRIMARY KEY (student_id, skill_id)
);

CREATE TABLE IF NOT EXISTS public.students
(
    student_id text COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    dob date,
    gender character varying(20) COLLATE pg_catalog."default",
    department_id uuid,
    semester integer,
    cgpa numeric(3, 2),
    attendance_percentage numeric(5, 2),
    research_experience boolean DEFAULT false,
    avatar_path character varying(500) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT students_pkey PRIMARY KEY (student_id),
    CONSTRAINT students_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id uuid NOT NULL DEFAULT gen_random_uuid(),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    profile_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    profile_ref_id text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    last_login timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.achievements
    ADD CONSTRAINT achievements_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.certifications
    ADD CONSTRAINT certifications_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.club_invitations
    ADD CONSTRAINT fk_invite_club FOREIGN KEY (club_id)
    REFERENCES public.clubs (club_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.club_invitations
    ADD CONSTRAINT fk_invite_student FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.club_memberships
    ADD CONSTRAINT club_memberships_club_id_fkey FOREIGN KEY (club_id)
    REFERENCES public.clubs (club_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.club_memberships
    ADD CONSTRAINT club_memberships_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.company_job_roles
    ADD CONSTRAINT company_job_roles_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.companies (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_company_job_roles_company_id
    ON public.company_job_roles(company_id);


ALTER TABLE IF EXISTS public.faculty
    ADD CONSTRAINT faculty_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.departments (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.internships
    ADD CONSTRAINT internships_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.placement_invitations
    ADD CONSTRAINT fk_pi_company FOREIGN KEY (company_id)
    REFERENCES public.companies (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.placement_invitations
    ADD CONSTRAINT fk_pi_job_role FOREIGN KEY (job_role_id)
    REFERENCES public.company_job_roles (job_role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.placement_invitations
    ADD CONSTRAINT fk_pi_student FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.placements
    ADD CONSTRAINT placements_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.companies (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.placements
    ADD CONSTRAINT placements_job_role_id_fkey FOREIGN KEY (job_role_id)
    REFERENCES public.company_job_roles (job_role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.placements
    ADD CONSTRAINT placements_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.publications
    ADD CONSTRAINT publications_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.research_project_participants
    ADD CONSTRAINT research_project_participants_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.research_projects (project_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_research_project_participants_project_id
    ON public.research_project_participants(project_id);


ALTER TABLE IF EXISTS public.research_project_participants
    ADD CONSTRAINT research_project_participants_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_research_project_participants_student_id
    ON public.research_project_participants(student_id);


ALTER TABLE IF EXISTS public.research_project_required_skills
    ADD CONSTRAINT research_project_required_skills_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.research_projects (project_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.research_project_required_skills
    ADD CONSTRAINT research_project_required_skills_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES public.skills (skill_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.research_projects
    ADD CONSTRAINT research_projects_faculty_id_fkey FOREIGN KEY (faculty_id)
    REFERENCES public.faculty (faculty_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.student_interests
    ADD CONSTRAINT student_interests_interest_id_fkey FOREIGN KEY (interest_id)
    REFERENCES public.interests (interest_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_student_interests_interest_id
    ON public.student_interests(interest_id);


ALTER TABLE IF EXISTS public.student_interests
    ADD CONSTRAINT student_interests_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_student_interests_student_id
    ON public.student_interests(student_id);


ALTER TABLE IF EXISTS public.student_skills
    ADD CONSTRAINT student_skills_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES public.skills (skill_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_student_skills_skill_id
    ON public.student_skills(skill_id);


ALTER TABLE IF EXISTS public.student_skills
    ADD CONSTRAINT student_skills_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_student_skills_student_id
    ON public.student_skills(student_id);


ALTER TABLE IF EXISTS public.students
    ADD CONSTRAINT students_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.departments (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_students_department_id
    ON public.students(department_id);

END;